# Generated by Django 2.2.3 on 2019-08-07 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import draft.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=2000)),
                ('portfolio_type', models.IntegerField()),
                ('attached_link', models.TextField(blank=True, max_length=1000)),
                ('attached_file', models.FileField(blank=True, upload_to=draft.models.directory_path_by_user)),
                ('attached_video_tag', models.TextField(blank=True, max_length=1000)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=2000)),
                ('activity_dt', models.DateField()),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
