# Generated by Django 2.2.3 on 2019-08-04 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='created_date',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='draftactivity',
            old_name='created_date',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='draftportfolio',
            old_name='created_date',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='draftresume',
            old_name='created_date',
            new_name='created_dt',
        ),
        migrations.AddField(
            model_name='draft',
            name='last_modified_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
