# Generated by Django 2.2.1 on 2019-08-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20190807_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftactivity',
            old_name='last_modified_user_id',
            new_name='last_modified_user',
        ),
        migrations.RenameField(
            model_name='draftportfolio',
            old_name='last_modified_user_id',
            new_name='last_modified_user',
        ),
        migrations.RenameField(
            model_name='draftresume',
            old_name='last_modified_user_id',
            new_name='last_modified_user',
        ),
        migrations.AlterField(
            model_name='draft',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
